#!/usr/bin/python3
fp = '/usr/share/kicad/template/fp-lib-table'
lns = []
found = False
with open(fp, 'r') as f:
    for ln in f:
        if 'name "kikit"' in ln:
            # Already there
            found = True
            break
        lns.append(ln)

if not found:
    lns.insert(-1, '  (lib (name "kikit")(type "KiCad")(uri "${KISYSMOD}/kikit.pretty")(options "")(descr "KiKit footprints"))\n')
    with open(fp, 'w') as f:
        f.writelines(lns)

lns = []
found = False
sy = '/usr/share/kicad/template/sym-lib-table'
with open(sy, 'r') as f:
    for ln in f:
        if 'name "kikit"' in ln:
            # Already there
            found = True
            break
        lns.append(ln)

if not found:
    lns.insert(-1, '  (lib (name "kikit")(type "KiCad")(uri "${KICAD6_SYMBOL_DIR}/kikit.kicad_sym")(options "")(descr "KiKit symbols"))\n')
    with open(sy, 'w') as f:
        f.writelines(lns)

