#!/usr/bin/python3
import os


def filter(fp):
    if not os.path.isfile(fp):
        return
    lns = []
    with open(fp, 'r') as f:
        for ln in f:
            if 'name "kikit"' not in ln:
               lns.append(ln)
    with open(fp, 'w') as f:
         f.writelines(lns)


filter('/usr/share/kicad/template/fp-lib-table')
filter('/usr/share/kicad/template/sym-lib-table')
filter('/usr/share/kicad-nightly/template/fp-lib-table')
filter('/usr/share/kicad-nightly/template/sym-lib-table')
