#!/usr/bin/python3
# -*- coding: utf-8 -*-
# Copyright (c) 2020-2022 Salvador E. Tropea
# Copyright (c) 2020-2022 Instituto Nacional de Tecnología Industrial
# License: GPL-3.0
# Project: KiBot (formerly KiPlot)
"""
 KiKit

 Wrapper to run it locally
"""
import sys
import os
dname = os.path.dirname(os.path.abspath(os.path.dirname(__file__)))
#sys.path.insert(0, os.path.join(dname, 'kikit'))
sys.path.insert(0, dname)
from kikit.ui import cli
cli()
